services:
  postgres_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: netdb_test
    ports:
      - "5432:5432"
    # Varmistetaan että tietokanta on luotu ennen testejä
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  api_test:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    depends_on:
      postgres_test:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:root@postgres_test:5432/netdb_test
      NODE_ENV: test
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: root
      TEST_DB_HOST: postgres_test
      TEST_DB_PORT: 5432
      TEST_DB_NAME: netdb_test
      JWT_ACCESS_SECRET: testsecret
      JWT_REFRESH_SECRET: testsecret
      DB_SSL: "false"
